# Reading https://docs.gitlab.com/ee/ci/examples/test-and-deploy-python-application-to-heroku.html
test:
    image: python:3.6
    script:
    - apt-get update -qy
    - pip3 install -r requirements.txt
    - pip3 install pytest
    - pytest

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
#  script:
#    - bundle exec jekyll build -d public/
  artifacts:
    paths:
      - /
  only:
    - master # this job will affect only the 'master' branch
