# Reading https://docs.gitlab.com/ee/ci/examples/test-and-deploy-python-application-to-heroku.html
test:
    script:
    - apt-get update -qy
    - apt-get install -y python3 python3-pip
    - pip3 install -r requirements.txt
    - pytest
    